name: Run Locust Tests on Commit
on:
  push:
    branches:
      - main
jobs:
  locust-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start Flask server
        run: |
          python server.py &
          echo "Waiting for Flask server to start"
          sleep 30
      - name: Replace 'weight =' occurrences in locustfile.py
        run: |
          sed -i '0,/weight = [0-9]*/!{s/weight = [0-9]*/weight = 0/}' locustfile.py
      - name: Verify weight changes
        run: |
          cat locustfile.py
      - name: Run Locust tests
        run: |
          locust -f locustfile.py --host=http://127.0.0.1:5000 --users 10000 --spawn-rate 100 --headless -t 2m
      - name: Stop Flask server
        run: |
          pkill -f "python server.py"
